import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import oauthRouter from "./oauth";
import passwordResetRouter from "./password-reset";
import emailVerificationRouter from "./email-verification";
import usersRouter from "./users";
import examsRouter from "./exams";
import questionsRouter from "./questions";
import registrationsRouter from "./registrations";
import submissionsRouter from "./submissions";
import leaderboardRouter from "./leaderboard";
import walletRouter from "./wallet";
import adminRouter from "./admin";
import avatarRouter from "./avatar";
import depositsRouter from "./deposits";
import withdrawalsRouter from "./withdrawals";
import verifyRouter from "./verify";
import bannersRouter from "./banners";
import categoriesRouter from "./categories";
import chatRouter from "./chat";
import blocksRouter from "./blocks";
import reportsRouter from "./reports";
import postsRouter from "./posts";
import reelsRouter from "./reels";
import notificationsRouter from "./notifications";
import rolesRouter from "./roles";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(oauthRouter);
router.use(passwordResetRouter);
router.use(emailVerificationRouter);
router.use(usersRouter);
router.use(examsRouter);
router.use(questionsRouter);
router.use(registrationsRouter);
router.use(submissionsRouter);
router.use(leaderboardRouter);
router.use(walletRouter);
router.use(adminRouter);
router.use(avatarRouter);
router.use(depositsRouter);
router.use(withdrawalsRouter);
router.use(verifyRouter);
router.use(bannersRouter);
router.use(categoriesRouter);
router.use(chatRouter);
router.use(blocksRouter);
router.use(reportsRouter);
router.use(postsRouter);
router.use(reelsRouter);
router.use(notificationsRouter);
router.use(rolesRouter);

export default router;
